language: java
jdk:
  - oraclejdk8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $TRAVIS_BUILD_DIR/build/libs/
dist: trusty
jobs:
  include:
    - stage: test
      script: ./gradlew check
    - stage: build
      script: ./gradlew build -x test
    - stage: build-docker-image-for-release
      script: ./scripts/docker-build-release.sh
    - stage: build-docker-image-for-dev
      script: ./scripts/docker-build-dev.sh
stages:
  - test
  - build
  - name: build-docker-image-for-release
    if: tag = /^v\d+\.\d+\.\d+$/
  - name: build-docker-image-for-dev
    if: tag = /^v\d+\.\d+\.\d+\.(beta|alpha).*$/
branches:
  only:
    - master
    - dev
    - /^v\d+\.\d+\.\d+.*$/
notifications:
  webhooks:
    - https://fathomless-fjord-24024.herokuapp.com/notify
