server:
  port: 8090

spring:
  output:
    ansi:
      enabled: always
  thymeleaf:
    cache: false

halo:
  security:
    oauth2:
      jwt:
        jwsAlgorithm: rs512
        public-key-location: classpath:app.pub
        private-key-location: classpath:app.key
  plugin:
    runtime-mode: development # development, deployment
    classes-directories:
      - "build/classes"
      - "build/resources"
    lib-directories:
      - "libs"
  work-dir: ${user.home}/halo2-dev
logging:
  level:
    run.halo.app: DEBUG
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
