server:
  port: 18090
  forward-headers-strategy: native
  compression:
    enabled: false
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  output:
    ansi:
      enabled: always
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:halo-test

    # H2 Database 配置
    #    driver-class-name: org.h2.Driver
    #    url: jdbc:h2:file:~/halo-test/db/halo
    #    username: admin
    #    password: 123456

    # MySQL 配置
  #  driver-class-name: com.mysql.cj.jdbc.Driver
  #  url: jdbc:mysql://127.0.0.1:3306/halodb?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
  #  username: root
  #  password: 123456

  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  flyway:
    enabled: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cache:
    type: none
management:
  endpoints:
    web:
      base-path: /api/admin/actuator
      exposure:
        include: ['httptrace', 'metrics','env','logfile']
logging:
  level:
    run.halo.app: DEBUG
    org.hibernate: ERROR
  file:
    path: ${user.home}/halo-test/logs

halo:
  doc-disabled: false
  auth-enable: false
  mode: test
  workDir: ${user.home}/halo-test/
