[versions]
lucene = '10.3.0'
resilience4j = '2.3.0'
therapi = '0.15.0'

[libraries]
lucene-core = { module = 'org.apache.lucene:lucene-core', version.ref = 'lucene' }
lucene-queryparser = { module = 'org.apache.lucene:lucene-queryparser', version.ref = 'lucene' }
lucene-highlighter = { module = 'org.apache.lucene:lucene-highlighter', version.ref = 'lucene' }
lucene-backward-codecs = { module = 'org.apache.lucene:lucene-backward-codecs', version.ref = 'lucene' }
lucene-analyzers-common = { module = 'org.apache.lucene:lucene-analysis-common', version.ref = 'lucene' }

therapi-runtime-javadoc = { module = 'com.github.therapi:therapi-runtime-javadoc', version.ref = 'therapi' }
therapi-runtime-javadoc-scribe = { module = 'com.github.therapi:therapi-runtime-javadoc-scribe', version.ref = 'therapi' }

resilience4j-springboot3 = { module = 'io.github.resilience4j:resilience4j-spring-boot3', version.ref = 'resilience4j' }
resilience4j-reactor = { module = 'io.github.resilience4j:resilience4j-reactor', version.ref = 'resilience4j' }

apache-commons-lang3 = 'org.apache.commons:commons-lang3:3.12.0'
apache-tika-core = 'org.apache.tika:tika-core:3.2.0'

encoding-base62 = 'io.seruco.encoding:base62:0.1.3'
pf4j = 'org.pf4j:pf4j:3.13.0'
guava = 'com.google.guava:guava:33.4.8-jre'
java-diff-utils = 'io.github.java-diff-utils:java-diff-utils:4.15'
jsoup = 'org.jsoup:jsoup:1.21.1'
json-patch = 'com.github.java-json-tools:json-patch:1.13'
springdoc-openapi = 'org.springdoc:springdoc-openapi-starter-webflux-ui:2.8.9'
openapi-schema-validator = 'org.openapi4j:openapi-schema-validator:1.0.7'
bouncycastle-bcpkix = 'org.bouncycastle:bcpkix-jdk18on:1.81'
twofactor-auth = 'com.j256.two-factor-auth:two-factor-auth:1.3'
imgscalr-lib = 'org.imgscalr:imgscalr-lib:4.2'
thumbnailator = 'net.coobird:thumbnailator:0.4.20'
metadata-extractor = 'com.drewnoakes:metadata-extractor:2.19.0'

[bundles]
lucene = ['lucene-core', 'lucene-queryparser', 'lucene-highlighter', 'lucene-backward-codecs', 'lucene-analyzers-common']
resilience4j = ['resilience4j-springboot3', 'resilience4j-reactor']
apache = ['apache-commons-lang3', 'apache-tika-core']
therapi = ['therapi-runtime-javadoc', 'therapi-runtime-javadoc-scribe']

[plugins]
spring-boot = 'org.springframework.boot:3.5.6'
spring-dependency-management = 'io.spring.dependency-management:1.1.7'
git-properties = 'com.gorylenko.gradle-git-properties:2.5.2'
undercouch-download = 'de.undercouch.download:5.6.0'
lombok = 'io.freefair.lombok:8.14'
checksum = 'org.gradle.crypto.checksum:1.4.0'
node = 'com.github.node-gradle.node:7.1.0'
openapi-generator = 'org.openapi.generator:7.12.0'
springdoc-openapi = 'org.springdoc.openapi-gradle-plugin:1.9.0'
versions = 'com.github.ben-manes.versions:0.52.0'
grgit = 'org.ajoberstar.grgit:5.3.3'
